title: Emoji
tagline: Emoji done right
description: Comprehensive PHP parser of emoticons, HTML entities, shortcodes and unicodes (emojis).
site_title: Emoji for PHP
google_analytics_tracking_id: #UA-137970568-1
repository: emoji
default_version: '1.0'
releases:
  next:
    '1.1':
      documentation_link: '/1.1/'
  current:
    '1.0':
      documentation_link: '/1.0/'
  previous:
#    '1.0':
#      documentation_link: '/1.0/'
author:
    name: Mark Carver
    twitter_account: _markcarver
    website: https://github.com/markcarver
highlights:
    description: "The PHP <code>Emoji</code> parser is a robust, based on the specification compliant <a href=\"https://emojibase.dev/\">Emojibase</a> project."
    features:
        - The only PHP library fully compatible with the Emojibase and CLDR specs
        - Feature 2
        - Feature 3
        - Easy-to-use API
composer: "$ composer require unicorn-fail/emoji"
